/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package student.information.system;

import java.awt.Component;
import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static student.information.system.login.invokersession;
import static student.information.system.login.usernamet;

/**
 *
 * @author home
 */
public class admin extends javax.swing.JFrame {

    /**
     * Creates new form admin
     */
    public admin() {
        initComponents();
        
        try {
          
           
            String title = TT.getText();
            
               
            conn db = new conn();
            Statement stmt = db.getconnect();
        
          TT.setText("");
     String querys = "SELECT * FROM `config` WHERE  id = '1';";
            ResultSet rs = stmt.executeQuery(querys);
         while (rs.next()) {
               // System.out.println("first name: " + rs.getString("email"));
               String titles  = rs.getString("schoolname");
               TT.setText(titles);
   
          
         
             String querys1 = "SELECT * FROM `config` WHERE id = '1'"; 
            ResultSet rs1 = stmt.executeQuery(querys1);
  
            while (rs1.next()) {
               // System.out.println("first name: " + rs.getString("email"));
               String idz = rs1.getString("id");
               String xd = rs1.getString("darkmode");
       
      
        if(xd.equals("0")){
           
            side.setBackground(new java.awt.Color(0, 51, 204));
            btnonoff.setText("OFF");
      
        }else if(xd.equals("1")){
             side.setBackground(new java.awt.Color(0, 0, 0));
            btnonoff.setText("ON");
       
            
        }
          
            }
             
       
         }
      
  
           } catch (SQLException ex) {
            System.out.println("error: " + ex.getMessage());
            
        }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    int math = 0;
    int science = 0;
     int english = 0;
      int tle = 0;
       int filifino = 0;
       int x = 0;
       String stdls ="";
       int has = 0;
       int click = 0;
       String pg = "";
       String pol = "";
      
       
    int sub = 0;
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        mother = new javax.swing.JPanel();
        side = new javax.swing.JPanel();
        fp = new javax.swing.JPanel();
        fpt = new javax.swing.JLabel();
        sp = new javax.swing.JPanel();
        spt = new javax.swing.JLabel();
        tp = new javax.swing.JPanel();
        tpt = new javax.swing.JLabel();
        ftp = new javax.swing.JPanel();
        fptt = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        paneltab = new javax.swing.JPanel();
        switcher = new javax.swing.JTabbedPane();
        admin_adduser = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        pos = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        cfullname = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        admin_setgrades = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        mathtf = new javax.swing.JTextField();
        sciencetf = new javax.swing.JTextField();
        englishtf = new javax.swing.JTextField();
        tletf = new javax.swing.JTextField();
        filtf = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        grading = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        tot = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        stdn = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        comx = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        ttt = new javax.swing.JLabel();
        m1 = new javax.swing.JLabel();
        s1 = new javax.swing.JLabel();
        e1 = new javax.swing.JLabel();
        t1 = new javax.swing.JLabel();
        f1 = new javax.swing.JLabel();
        m2 = new javax.swing.JLabel();
        s2 = new javax.swing.JLabel();
        e2 = new javax.swing.JLabel();
        t2 = new javax.swing.JLabel();
        f2 = new javax.swing.JLabel();
        m3 = new javax.swing.JLabel();
        s3 = new javax.swing.JLabel();
        e3 = new javax.swing.JLabel();
        t3 = new javax.swing.JLabel();
        f3 = new javax.swing.JLabel();
        m4 = new javax.swing.JLabel();
        s4 = new javax.swing.JLabel();
        e4 = new javax.swing.JLabel();
        t4 = new javax.swing.JLabel();
        jLabel66 = new javax.swing.JLabel();
        f4 = new javax.swing.JLabel();
        fgt = new javax.swing.JLabel();
        sgt = new javax.swing.JLabel();
        tgt = new javax.swing.JLabel();
        fc = new javax.swing.JLabel();
        admin_managestudents = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        ssx = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        notex = new javax.swing.JTextArea();
        notbtn = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        statusz = new javax.swing.JLabel();
        Settings = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btnonoff = new javax.swing.JToggleButton();
        jLabel24 = new javax.swing.JLabel();
        jToggleButton2 = new javax.swing.JToggleButton();
        CPPANEL = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        oldx = new javax.swing.JTextField();
        newp = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        TT = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        mother.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        side.setBackground(new java.awt.Color(0, 51, 204));

        fp.setBackground(new java.awt.Color(204, 204, 204));

        fpt.setText("ADD USERS");
        fpt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fptMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout fpLayout = new javax.swing.GroupLayout(fp);
        fp.setLayout(fpLayout);
        fpLayout.setHorizontalGroup(
            fpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fpLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(fpt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        fpLayout.setVerticalGroup(
            fpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fpt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                spMouseClicked(evt);
            }
        });

        spt.setText("Manage Grades");
        spt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sptMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout spLayout = new javax.swing.GroupLayout(sp);
        sp.setLayout(spLayout);
        spLayout.setHorizontalGroup(
            spLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(spLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(spt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        spLayout.setVerticalGroup(
            spLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(spLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tpMouseEntered(evt);
            }
        });

        tpt.setText("Manage Student");
        tpt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tptMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout tpLayout = new javax.swing.GroupLayout(tp);
        tp.setLayout(tpLayout);
        tpLayout.setHorizontalGroup(
            tpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tpLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(tpt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tpLayout.setVerticalGroup(
            tpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tpt, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ftp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ftpMouseClicked(evt);
            }
        });

        fptt.setText("Settings");
        fptt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fpttMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ftpLayout = new javax.swing.GroupLayout(ftp);
        ftp.setLayout(ftpLayout);
        ftpLayout.setHorizontalGroup(
            ftpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ftpLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(fptt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ftpLayout.setVerticalGroup(
            ftpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ftpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fptt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Arial Unicode MS", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("ADMIN PANEL");

        javax.swing.GroupLayout sideLayout = new javax.swing.GroupLayout(side);
        side.setLayout(sideLayout);
        sideLayout.setHorizontalGroup(
            sideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sideLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ftp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
            .addGroup(sideLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        sideLayout.setVerticalGroup(
            sideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel8)
                .addGap(42, 42, 42)
                .addComponent(fp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(sp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ftp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(327, Short.MAX_VALUE))
        );

        paneltab.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("ADD USERS");

        jLabel15.setText("Fullname");

        jLabel16.setText("Username");

        jLabel17.setText("Password");

        pos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Student", "Teacher" }));
        pos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posActionPerformed(evt);
            }
        });

        jLabel18.setText("Position");

        jButton2.setText("Ok");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout admin_adduserLayout = new javax.swing.GroupLayout(admin_adduser);
        admin_adduser.setLayout(admin_adduserLayout);
        admin_adduserLayout.setHorizontalGroup(
            admin_adduserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(admin_adduserLayout.createSequentialGroup()
                .addGroup(admin_adduserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(admin_adduserLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel6))
                    .addGroup(admin_adduserLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(admin_adduserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(admin_adduserLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(18, 18, 18)
                                .addComponent(pos, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(admin_adduserLayout.createSequentialGroup()
                                .addGroup(admin_adduserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(admin_adduserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField1)
                                    .addComponent(jTextField2)
                                    .addGroup(admin_adduserLayout.createSequentialGroup()
                                        .addComponent(cfullname, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        admin_adduserLayout.setVerticalGroup(
            admin_adduserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(admin_adduserLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel6)
                .addGap(43, 43, 43)
                .addGroup(admin_adduserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(cfullname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(admin_adduserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(admin_adduserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(admin_adduserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(399, Short.MAX_VALUE))
        );

        switcher.addTab("tab1", admin_adduser);

        jLabel4.setText("Set Grades");

        jLabel1.setText("Student Name");

        jLabel2.setText("Math");

        jLabel3.setText("Science");

        jLabel9.setText("English");

        jLabel10.setText("TLE");

        jLabel11.setText("Filifino");

        mathtf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                mathtfFocusGained(evt);
            }
        });
        mathtf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mathtfMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mathtfMousePressed(evt);
            }
        });
        mathtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mathtfActionPerformed(evt);
            }
        });
        mathtf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mathtfKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mathtfKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mathtfKeyTyped(evt);
            }
        });

        sciencetf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sciencetfActionPerformed(evt);
            }
        });
        sciencetf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sciencetfKeyPressed(evt);
            }
        });

        englishtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                englishtfActionPerformed(evt);
            }
        });

        tletf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tletfActionPerformed(evt);
            }
        });

        filtf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtfActionPerformed(evt);
            }
        });
        filtf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                filtfKeyPressed(evt);
            }
        });

        jButton1.setText("SET");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        grading.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "First Grading", "Second Grading", "Third Grading", "Fourth Grading" }));

        jLabel13.setText("Semester");

        jLabel14.setText("Total Average");

        stdn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                stdnKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                stdnKeyReleased(evt);
            }
        });

        jLabel19.setText("Check Grades");

        comx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Student" }));
        comx.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comxMouseClicked(evt);
            }
        });
        comx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comxActionPerformed(evt);
            }
        });

        jPanel1.setLayout(null);
        jPanel1.add(jSeparator6);
        jSeparator6.setBounds(10, 20, 270, 2);

        jLabel33.setText("Subjects");
        jPanel1.add(jLabel33);
        jLabel33.setBounds(40, 0, 50, 14);

        jLabel34.setText("1");
        jPanel1.add(jLabel34);
        jLabel34.setBounds(110, 0, 10, 14);

        jLabel35.setText("2");
        jPanel1.add(jLabel35);
        jLabel35.setBounds(140, 0, 20, 14);

        jLabel36.setText("3");
        jPanel1.add(jLabel36);
        jLabel36.setBounds(170, 0, 20, 14);

        jLabel37.setText("4");
        jPanel1.add(jLabel37);
        jLabel37.setBounds(200, 0, 20, 14);

        jLabel38.setText("Total");
        jPanel1.add(jLabel38);
        jLabel38.setBounds(240, 0, 40, 14);
        jPanel1.add(jSeparator7);
        jSeparator7.setBounds(0, 130, 300, 0);

        jSeparator10.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator10);
        jSeparator10.setBounds(220, 20, 10, 170);

        jSeparator11.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator11);
        jSeparator11.setBounds(90, 20, 10, 170);

        jSeparator12.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator12);
        jSeparator12.setBounds(120, 20, 10, 170);

        jSeparator13.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator13);
        jSeparator13.setBounds(150, 20, 20, 170);

        jSeparator14.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator14);
        jSeparator14.setBounds(180, 20, 20, 170);

        jLabel39.setText("Math");
        jPanel1.add(jLabel39);
        jLabel39.setBounds(40, 30, 50, 14);

        jLabel40.setText("Science");
        jPanel1.add(jLabel40);
        jLabel40.setBounds(40, 50, 50, 20);

        jLabel41.setText("English");
        jPanel1.add(jLabel41);
        jLabel41.setBounds(40, 70, 50, 14);

        jLabel42.setText("TLE");
        jPanel1.add(jLabel42);
        jLabel42.setBounds(40, 90, 50, 14);

        jLabel43.setText("Filifino");
        jPanel1.add(jLabel43);
        jLabel43.setBounds(40, 110, 50, 14);

        ttt.setText("0");
        jPanel1.add(ttt);
        ttt.setBounds(240, 140, 40, 14);

        m1.setText("0");
        jPanel1.add(m1);
        m1.setBounds(100, 30, 30, 14);

        s1.setText("0");
        jPanel1.add(s1);
        s1.setBounds(100, 50, 30, 14);

        e1.setText("0");
        jPanel1.add(e1);
        e1.setBounds(100, 70, 40, 14);

        t1.setText("0");
        jPanel1.add(t1);
        t1.setBounds(100, 90, 40, 14);

        f1.setText("0");
        jPanel1.add(f1);
        f1.setBounds(100, 110, 30, 14);

        m2.setText("0");
        jPanel1.add(m2);
        m2.setBounds(130, 30, 30, 14);

        s2.setText("0");
        jPanel1.add(s2);
        s2.setBounds(130, 50, 30, 14);

        e2.setText("0");
        jPanel1.add(e2);
        e2.setBounds(130, 70, 30, 14);

        t2.setText("0");
        jPanel1.add(t2);
        t2.setBounds(130, 90, 30, 14);

        f2.setText("0");
        jPanel1.add(f2);
        f2.setBounds(130, 110, 30, 14);

        m3.setText("0");
        jPanel1.add(m3);
        m3.setBounds(160, 30, 30, 14);

        s3.setText("0");
        jPanel1.add(s3);
        s3.setBounds(160, 50, 30, 14);

        e3.setText("0");
        jPanel1.add(e3);
        e3.setBounds(160, 70, 30, 14);

        t3.setText("0");
        jPanel1.add(t3);
        t3.setBounds(160, 90, 30, 14);

        f3.setText("0");
        jPanel1.add(f3);
        f3.setBounds(160, 110, 30, 14);

        m4.setText("0");
        jPanel1.add(m4);
        m4.setBounds(190, 30, 30, 14);

        s4.setText("0");
        jPanel1.add(s4);
        s4.setBounds(190, 50, 30, 14);

        e4.setText("0");
        jPanel1.add(e4);
        e4.setBounds(190, 70, 30, 14);

        t4.setText("0");
        jPanel1.add(t4);
        t4.setBounds(190, 90, 30, 14);

        jLabel66.setText("Total");
        jPanel1.add(jLabel66);
        jLabel66.setBounds(40, 140, 40, 14);

        f4.setText("0");
        jPanel1.add(f4);
        f4.setBounds(190, 110, 30, 14);

        fgt.setText("0");
        jPanel1.add(fgt);
        fgt.setBounds(100, 140, 40, 14);

        sgt.setText("0");
        jPanel1.add(sgt);
        sgt.setBounds(130, 140, 40, 14);

        tgt.setText("0");
        jPanel1.add(tgt);
        tgt.setBounds(160, 140, 40, 14);

        fc.setText("0");
        jPanel1.add(fc);
        fc.setBounds(200, 140, 20, 14);

        javax.swing.GroupLayout admin_setgradesLayout = new javax.swing.GroupLayout(admin_setgrades);
        admin_setgrades.setLayout(admin_setgradesLayout);
        admin_setgradesLayout.setHorizontalGroup(
            admin_setgradesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, admin_setgradesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(admin_setgradesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(admin_setgradesLayout.createSequentialGroup()
                        .addGroup(admin_setgradesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addGroup(admin_setgradesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, admin_setgradesLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(grading, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(admin_setgradesLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(admin_setgradesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tot, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                    .addComponent(jLabel12)
                                    .addComponent(mathtf)
                                    .addComponent(sciencetf)
                                    .addComponent(englishtf)
                                    .addComponent(tletf)
                                    .addComponent(filtf)
                                    .addComponent(stdn))
                                .addGap(17, 17, 17)))))
                .addGap(58, 58, 58))
            .addComponent(jSeparator1)
            .addGroup(admin_setgradesLayout.createSequentialGroup()
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(admin_setgradesLayout.createSequentialGroup()
                .addGroup(admin_setgradesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(admin_setgradesLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(admin_setgradesLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel19)
                        .addGap(65, 65, 65)
                        .addComponent(comx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        admin_setgradesLayout.setVerticalGroup(
            admin_setgradesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, admin_setgradesLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel4)
                .addGap(9, 9, 9)
                .addGroup(admin_setgradesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(stdn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(admin_setgradesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(mathtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(admin_setgradesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(sciencetf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(admin_setgradesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(englishtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(admin_setgradesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tletf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(admin_setgradesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(filtf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(admin_setgradesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(grading, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(admin_setgradesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(admin_setgradesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(comx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(55, 55, 55))
        );

        switcher.addTab("tab2", admin_setgrades);

        jLabel5.setText("Manage Student");

        ssx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Student" }));
        ssx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ssxActionPerformed(evt);
            }
        });

        jLabel20.setText("Students");

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Drop");
        jLabel21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel21MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("ADD NOTE");
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        notex.setColumns(20);
        notex.setRows(5);
        notex.setVisible(false);
        jScrollPane1.setViewportView(notex);

        notbtn.setText("OK");
        notbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                notbtnMouseClicked(evt);
            }
        });

        jLabel23.setText("Student Status:");

        statusz.setText("N/A");

        javax.swing.GroupLayout admin_managestudentsLayout = new javax.swing.GroupLayout(admin_managestudents);
        admin_managestudents.setLayout(admin_managestudentsLayout);
        admin_managestudentsLayout.setHorizontalGroup(
            admin_managestudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(admin_managestudentsLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, admin_managestudentsLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(admin_managestudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, admin_managestudentsLayout.createSequentialGroup()
                        .addGroup(admin_managestudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(admin_managestudentsLayout.createSequentialGroup()
                                .addComponent(notbtn)
                                .addGap(8, 8, 8)))
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, admin_managestudentsLayout.createSequentialGroup()
                        .addGroup(admin_managestudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, admin_managestudentsLayout.createSequentialGroup()
                        .addGroup(admin_managestudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(admin_managestudentsLayout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addGap(18, 18, 18)
                                .addComponent(statusz))
                            .addGroup(admin_managestudentsLayout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ssx, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(29, 29, 29))))
        );
        admin_managestudentsLayout.setVerticalGroup(
            admin_managestudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(admin_managestudentsLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel5)
                .addGap(38, 38, 38)
                .addGroup(admin_managestudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ssx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(18, 18, 18)
                .addGroup(admin_managestudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(statusz))
                .addGap(20, 20, 20)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(notbtn)
                .addContainerGap(221, Short.MAX_VALUE))
        );

        switcher.addTab("tab3", admin_managestudents);

        jLabel7.setText("Settings");

        btnonoff.setText("OFF");
        btnonoff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnonoffMouseClicked(evt);
            }
        });

        jLabel24.setText("Dark Mode");

        jToggleButton2.setText("Log out");
        jToggleButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton2MouseClicked(evt);
            }
        });

        CPPANEL.setBackground(new java.awt.Color(0, 0, 153));
        CPPANEL.setForeground(new java.awt.Color(102, 102, 102));

        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Change Password");

        jButton4.setText("Change Password");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("OLD PASSWORD:");

        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("NEW PASSWORD");

        javax.swing.GroupLayout CPPANELLayout = new javax.swing.GroupLayout(CPPANEL);
        CPPANEL.setLayout(CPPANELLayout);
        CPPANELLayout.setHorizontalGroup(
            CPPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CPPANELLayout.createSequentialGroup()
                .addGroup(CPPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CPPANELLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(CPPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(jLabel27))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CPPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newp, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(oldx, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(CPPANELLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel26))
                    .addGroup(CPPANELLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        CPPANELLayout.setVerticalGroup(
            CPPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CPPANELLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26)
                .addGap(18, 18, 18)
                .addGroup(CPPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oldx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CPPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addContainerGap())
        );

        jButton3.setText("Change Password");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel28.setText("LOG IN TITLE");

        jButton5.setText("Change");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout SettingsLayout = new javax.swing.GroupLayout(Settings);
        Settings.setLayout(SettingsLayout);
        SettingsLayout.setHorizontalGroup(
            SettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SettingsLayout.createSequentialGroup()
                .addGroup(SettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SettingsLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(SettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SettingsLayout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addGap(18, 18, 18)
                                .addComponent(btnonoff))
                            .addComponent(jToggleButton2)
                            .addComponent(jButton3)))
                    .addGroup(SettingsLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel7))
                    .addGroup(SettingsLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TT, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)))
                .addContainerGap(11, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SettingsLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(CPPANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        SettingsLayout.setVerticalGroup(
            SettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SettingsLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(SettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(btnonoff))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton2)
                .addGap(4, 4, 4)
                .addGroup(SettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(TT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CPPANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(312, Short.MAX_VALUE))
        );

        switcher.addTab("tab4", Settings);

        paneltab.add(switcher, new org.netbeans.lib.awtextra.AbsoluteConstraints(-12, -36, 310, 650));

        javax.swing.GroupLayout motherLayout = new javax.swing.GroupLayout(mother);
        mother.setLayout(motherLayout);
        motherLayout.setHorizontalGroup(
            motherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(motherLayout.createSequentialGroup()
                .addComponent(side, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(paneltab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        motherLayout.setVerticalGroup(
            motherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(motherLayout.createSequentialGroup()
                .addGroup(motherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paneltab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(side, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mother, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mother, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fptMouseClicked
   
    
        switcher.setSelectedIndex(0);
        fpt.setForeground(new java.awt.Color(204, 204, 204));
        fptt.setForeground(new java.awt.Color(0, 0, 0));
        spt.setForeground(new java.awt.Color(0, 0, 0));
        tpt.setForeground(new java.awt.Color(0, 0, 0));
        

     fp.setBackground(new java.awt.Color(0, 51, 204));
     sp.setBackground(new java.awt.Color(204, 204, 204));
      tp.setBackground(new java.awt.Color(204, 204, 204));
       ftp.setBackground(new java.awt.Color(204, 204, 204));
        
    }//GEN-LAST:event_fptMouseClicked

    private void sptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sptMouseClicked
    
        try {
          
            conn db = new conn();
            Statement stmt = db.getconnect();
            switcher.setSelectedIndex(1);
        spt.setForeground(new java.awt.Color(204, 204, 204));
        fptt.setForeground(new java.awt.Color(0, 0, 0));
        fpt.setForeground(new java.awt.Color(0, 0, 0));
        tpt.setForeground(new java.awt.Color(0, 0, 0));
 
     sp.setBackground(new java.awt.Color(0, 51, 204));
     fp.setBackground(new java.awt.Color(204, 204, 204));
      tp.setBackground(new java.awt.Color(204, 204, 204));
       ftp.setBackground(new java.awt.Color(204, 204, 204));
   
        

              String querys = "select * from users where previllege = 0;"; 
            ResultSet rs = stmt.executeQuery(querys);
  comx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Student" }));

         



            while (rs.next()) {
              
             String fnz = rs.getString("fullname");
              
              comx.addItem(fnz);
            

            }
                     
                
    
             
        } catch (SQLException ex) {
            System.out.println("error: " + ex.getMessage());
        }
        
     
     
        
    }//GEN-LAST:event_sptMouseClicked

    private void tpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tpMouseClicked
   
    }//GEN-LAST:event_tpMouseClicked

    private void ftpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ftpMouseClicked
           
    }//GEN-LAST:event_ftpMouseClicked

    private void tpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tpMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tpMouseEntered

    private void tptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tptMouseClicked
              
 try {
          
            conn db = new conn();
            Statement stmt = db.getconnect();
            switcher.setSelectedIndex(1);
          switcher.setSelectedIndex(2);
              tpt.setForeground(new java.awt.Color(204, 204, 204));
        fptt.setForeground(new java.awt.Color(0, 0, 0));
        spt.setForeground(new java.awt.Color(0, 0, 0));
        fpt.setForeground(new java.awt.Color(0, 0, 0));
notex.setVisible(false);
     tp.setBackground(new java.awt.Color(0, 51, 204));
     fp.setBackground(new java.awt.Color(204, 204, 204));
      sp.setBackground(new java.awt.Color(204, 204, 204));
       ftp.setBackground(new java.awt.Color(204, 204, 204));
       ssx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Student" }));
   
        
         notbtn.setVisible(false);

              String querys = "select * from users where previllege = 0;"; 
            ResultSet rs = stmt.executeQuery(querys);
  comx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Student" }));

         



            while (rs.next()) {
              
             String fnz = rs.getString("fullname");
            
              
                  ssx.addItem(fnz);
              
              
            

            }
                     
                
    
             
        } catch (SQLException ex) {
            System.out.println("error: " + ex.getMessage());
        }
        
     
    }//GEN-LAST:event_tptMouseClicked

    private void fpttMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fpttMouseClicked
   switcher.setSelectedIndex(3);
              fptt.setForeground(new java.awt.Color(204, 204, 204));
fpt.setForeground(new java.awt.Color(0, 0, 0));
        spt.setForeground(new java.awt.Color(0, 0, 0));
        tpt.setForeground(new java.awt.Color(0, 0, 0));
        
        
        
        
        
     ftp.setBackground(new java.awt.Color(0, 51, 204));
     fp.setBackground(new java.awt.Color(204, 204, 204));
      tp.setBackground(new java.awt.Color(204, 204, 204));
       sp.setBackground(new java.awt.Color(204, 204, 204));        // TODO add your handling code here:
    }//GEN-LAST:event_fpttMouseClicked

    private void mathtfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mathtfMouseClicked
     
    }//GEN-LAST:event_mathtfMouseClicked

    private void mathtfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mathtfKeyTyped
       
    }//GEN-LAST:event_mathtfKeyTyped

    private void mathtfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mathtfFocusGained
          
    }//GEN-LAST:event_mathtfFocusGained

    private void mathtfKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mathtfKeyReleased
     
    }//GEN-LAST:event_mathtfKeyReleased

    private void sciencetfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sciencetfKeyPressed
  
      
    }//GEN-LAST:event_sciencetfKeyPressed

    private void mathtfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mathtfKeyPressed
      

    }//GEN-LAST:event_mathtfKeyPressed

    private void filtfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filtfKeyPressed
  
    }//GEN-LAST:event_filtfKeyPressed

    private void mathtfMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mathtfMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_mathtfMousePressed

    private void mathtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mathtfActionPerformed
           String m = mathtf.getText();
           math = Integer.parseInt(m);
            int y = math+science+english+tle+filifino;
           x = y/5;
           String conv = Integer.toString(x);
           tot.setText(conv);
           
    }//GEN-LAST:event_mathtfActionPerformed

    private void sciencetfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sciencetfActionPerformed
         String s = sciencetf.getText();
           science = Integer.parseInt(s);
           int y = math+science+english+tle+filifino;
           x = y/5;
           
           String conv = Integer.toString(x);
           tot.setText(conv);
    }//GEN-LAST:event_sciencetfActionPerformed

    private void englishtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_englishtfActionPerformed
        String e = englishtf.getText();
           english = Integer.parseInt(e);
           int y = math+science+english+tle+filifino;
           x = y/5;
           
           String conv = Integer.toString(x);
           tot.setText(conv);
    }//GEN-LAST:event_englishtfActionPerformed

    private void tletfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tletfActionPerformed
          String t = tletf.getText();
           tle = Integer.parseInt(t);
           int y = math+science+english+tle+filifino;
           x = y/5;
           
           String conv = Integer.toString(x);
           tot.setText(conv);
    }//GEN-LAST:event_tletfActionPerformed

    private void filtfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtfActionPerformed
          String f = filtf.getText();
           filifino = Integer.parseInt(f);
           int y = math+science+english+tle+filifino;
           x = y/5;
           
           String conv = Integer.toString(x);
           tot.setText(conv);
    }//GEN-LAST:event_filtfActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        
             String  w = (String) grading.getSelectedItem();
         
        if(w.equals("First Grading")){
        try {
          
           
            String m = mathtf.getText();
             String s = sciencetf.getText();
             String e = englishtf.getText();
             String t = tletf.getText();
               String f = filtf.getText();
               String fullnam = stdn.getText();
               
            conn db = new conn();
            Statement stmt = db.getconnect();
             String query = "UPDATE grades1\n" +
"SET math='"+m+"', science='"+s+"', english ='"+e+"', filifino='"+f+"', tle='"+t+"'\n" +
"WHERE fullname='"+fullnam+"'"; 
            stmt.execute(query);
            System.out.println(fullnam);
             stdn.setText("");
         mathtf.setText("");
         sciencetf.setText("");
         englishtf.setText("");
         tletf.setText("");
         filtf.setText("");
  
           } catch (SQLException ex) {
            System.out.println("error: " + ex.getMessage());
            
        }
       }else if(w.equals("Second Grading")){
        try {
          
           
            String m = mathtf.getText();
             String s = sciencetf.getText();
             String e = englishtf.getText();
             String t = tletf.getText();
               String f = filtf.getText();
               String fullnam = stdn.getText();
               
               
            conn db = new conn();
            Statement stmt = db.getconnect();
             String query = "UPDATE grades2\n" +
"SET math='"+m+"', science='"+s+"', english ='"+e+"', filifino='"+f+"', tle='"+t+"'\n" +
"WHERE fullname='"+fullnam+"'"; 
            stmt.execute(query);
            System.out.println(fullnam);
             stdn.setText("");
         mathtf.setText("");
         sciencetf.setText("");
         englishtf.setText("");
         tletf.setText("");
         filtf.setText("");
          Component frame = null;
                      JOptionPane.showMessageDialog(frame,
    "OK",
    "Sucess",
    JOptionPane.OK_OPTION);
  
           } catch (SQLException ex) {
            System.out.println("error: " + ex.getMessage());
        }
       }if(w.equals("Third Grading")){
        try {
          
           
            String m = mathtf.getText();
             String s = sciencetf.getText();
             String e = englishtf.getText();
             String t = tletf.getText();
               String f = filtf.getText();
               String fullnam = stdn.getText();
               
            conn db = new conn();
            Statement stmt = db.getconnect();
             String query = "UPDATE grades3\n" +
"SET math='"+m+"', science='"+s+"', english ='"+e+"', filifino='"+f+"', tle='"+t+"'\n" +
"WHERE fullname='"+fullnam+"'"; 
            stmt.execute(query);
            System.out.println(fullnam);
             stdn.setText("");
         mathtf.setText("");
         sciencetf.setText("");
         englishtf.setText("");
         tletf.setText("");
         filtf.setText("");
   Component frame = null;
                      JOptionPane.showMessageDialog(frame,
    "OK",
    "Sucess",
    JOptionPane.OK_OPTION);
           } catch (SQLException ex) {
            System.out.println("error: " + ex.getMessage());
        }
       }if(w.equals("Fourth Grading")){
        try {
          
           
            String m = mathtf.getText();
             String s = sciencetf.getText();
             String e = englishtf.getText();
             String t = tletf.getText();
               String f = filtf.getText();
               String fullnam = stdn.getText();
               
            conn db = new conn();
            Statement stmt = db.getconnect();
             String query = "UPDATE grades4\n" +
"SET math='"+m+"', science='"+s+"', english ='"+e+"', filifino='"+f+"', tle='"+t+"'\n" +
"WHERE fullname='"+fullnam+"'"; 
            stmt.execute(query);
            System.out.println(fullnam);
             stdn.setText("");
         mathtf.setText("");
         sciencetf.setText("");
         englishtf.setText("");
         tletf.setText("");
         filtf.setText("");
   Component frame = null;
                      JOptionPane.showMessageDialog(frame,
    "OK",
    "Sucess",
    JOptionPane.OK_OPTION);
           } catch (SQLException ex) {
            System.out.println("error: " + ex.getMessage());
        }
       }
          
         
                   
    }//GEN-LAST:event_jButton1MouseClicked

    private void stdnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_stdnKeyPressed
        stdls = stdn.getText();
        System.out.println(stdls);
    }//GEN-LAST:event_stdnKeyPressed

    private void stdnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_stdnKeyReleased

    }//GEN-LAST:event_stdnKeyReleased

    private void posActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_posActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
          String  c = (String) pos.getSelectedItem();
          if(c.equals("Teacher")){
                  try {
            conn db = new conn();
            Statement stmt = db.getconnect();
            String ccfullname = cfullname.getText();
            String ccusername = jTextField2.getText();
            String ccpassword = jTextField1.getText();
           String current= ccpassword;
        MessageDigest m=MessageDigest.getInstance("MD5");
        m.update(current.getBytes(),0,current.length());
        String passwordl = new BigInteger(1,m.digest()).toString(16);
                String query = "insert into users(`fullname``password`, `previllege`)"
                    + " values('"+ccfullname+"', '"+ccusername+"', '"+passwordl+"', '1')"; 
                  stmt.execute(query);
                cfullname.setText("");
           jTextField2.setText("");
            jTextField1.setText("");
           Component frame = null;
                      JOptionPane.showMessageDialog(frame,
    "OK",
    "Sucess",
    JOptionPane.OK_OPTION);
  
            
            
        }     catch (NoSuchAlgorithmException ex) {
                  Logger.getLogger(admin.class.getName()).log(Level.SEVERE, null, ex);
              } catch (SQLException ex) {
                  Logger.getLogger(admin.class.getName()).log(Level.SEVERE, null, ex);
              }
        
          }else if(c.equals("Student"))
          {
                      try {
            conn db = new conn();
            Statement stmt = db.getconnect();
            String ccfullname = cfullname.getText();
            String ccusername = jTextField2.getText();
            String ccpassword = jTextField1.getText();
           String current= ccpassword;
        MessageDigest m=MessageDigest.getInstance("MD5");
        m.update(current.getBytes(),0,current.length());
        String passwordl = new BigInteger(1,m.digest()).toString(16);
                String query = "insert into users(`fullname`, `username`, `password`, `previllege`)"
                    + " values('"+ccfullname+"', '"+ccusername+"', '"+passwordl+"', '0')"; 
            stmt.execute(query);
               String queryx = "insert into grades1(`fullname`, `math`, `science`, `english`, `tle`, `filifino`)"
                    + " values('"+ccfullname+"', '0', '0', '0', '0', '0')"; 
            stmt.execute(queryx);
             String queryxz = "insert into grades2(`fullname`, `math`, `science`, `english`, `tle`, `filifino`)"
                    + " values('"+ccfullname+"', '0', '0', '0', '0', '0')"; 
            stmt.execute(queryxz);
             String queryx1 = "insert into grades3(`fullname`, `math`, `science`, `english`, `tle`, `filifino`)"
                    + " values('"+ccfullname+"', '0', '0', '0', '0', '0')"; 
            stmt.execute(queryx1);
             String queryx12 = "insert into grades4(`fullname`, `math`, `science`, `english`, `tle`, `filifino`)"
                    + " values('"+ccfullname+"', '0', '0', '0', '0', '0')"; 
            stmt.execute(queryx12);
            
                  cfullname.setText("");
           jTextField2.setText("");
            jTextField1.setText("");
           Component frame = null;
                      JOptionPane.showMessageDialog(frame,
    "OK",
    "Sucess",
    JOptionPane.OK_OPTION);
  
            
            
        } catch (SQLException ex) {
            System.out.println("error: " + ex.getMessage());
        }     catch (NoSuchAlgorithmException ex) {
                  Logger.getLogger(admin.class.getName()).log(Level.SEVERE, null, ex);
              }
          }
         
    }//GEN-LAST:event_jButton2MouseClicked

    private void comxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comxMouseClicked

        
    }//GEN-LAST:event_comxMouseClicked

    private void comxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comxActionPerformed
       if (comx.getSelectedItem().equals("Select Student"))
       {
         m1.setText("0");
                       s1.setText("0");
                       e1.setText("0");
                       t1.setText("0");
                       f1.setText("0");
                       m2.setText("0");
                       s2.setText("0");
                       e2.setText("0");
                       t2.setText("0");
                       f2.setText("0");
                       m3.setText("0");
                       s3.setText("0");
                       e3.setText("0");
                       t3.setText("0");
                       f3.setText("0");
                       m4.setText("0");
                       s4.setText("0");
                       e4.setText("0");
                       t4.setText("0");
                       f4.setText("0");
                       fgt.setText("0");
                       sgt.setText("0");
                       fc.setText("0");
                       ttt.setText("0");
                       tgt.setText("0");
       }else{
             try {
            conn db = new conn();
            Statement stmt = db.getconnect();
            
          
    String  c = (String) comx.getSelectedItem();
             
       
          String querys = "SELECT * FROM `grades1` WHERE  fullname = '"+c+"';";
            ResultSet rs = stmt.executeQuery(querys);
         
 
            while (rs.next()) {
               // System.out.println("first name: " + rs.getString("email"));
               String mf  = rs.getString("math");
                 String sf  = rs.getString("science");
                   String ef  = rs.getString("english");
                     String tf  = rs.getString("tle");
                       String filf  = rs.getString("filifino");
                       m1.setText(mf);
                       s1.setText(sf);
                       e1.setText(ef);
                       t1.setText(tf);
                       f1.setText(filf);
                       int m1int = Integer.parseInt(mf);
                       int s1int = Integer.parseInt(sf);
                       int e1int = Integer.parseInt(ef);
                       int t1int = Integer.parseInt(tf);
                       int f1int = Integer.parseInt(filf);
                       
                       int sototal = m1int+s1int+e1int+t1int+f1int;
                       int total = sototal/5;
                       String totos = String.valueOf(total);
                       fgt.setText(totos);
                       
                          String querys1 = "SELECT * FROM `grades2` WHERE fullname = '"+c+"';";
            ResultSet rs1 = stmt.executeQuery(querys1);
                       while(rs1.next()){
                           
                                   String ms  = rs1.getString("math");
                 String ss  = rs1.getString("science");
                   String es  = rs1.getString("english");
                     String ts  = rs1.getString("tle");
                       String fils  = rs1.getString("filifino");
                       m2.setText(ms);
                       s2.setText(ss);
                       e2.setText(es);
                       t2.setText(ts);
                       f2.setText(fils);
                        int m2int = Integer.parseInt(ms);
                       int s2int = Integer.parseInt(ss);
                       int e2int = Integer.parseInt(es);
                       int t2int = Integer.parseInt(ts);
                       int f2int = Integer.parseInt(fils);
                       
                       int sototal2 = m2int+s2int+e2int+t2int+f2int;
                       int total2 = sototal2 /5;
                       String totos2 = String.valueOf(total2);
                       sgt.setText(totos2);
                       String querys2 = "SELECT * FROM `grades3` WHERE fullname = '"+c+"';";
            ResultSet rs2 = stmt.executeQuery(querys2);
            
            while(rs2.next()){
                             String mt  = rs2.getString("math");
                 String st  = rs2.getString("science");
                   String et  = rs2.getString("english");
                     String tt  = rs2.getString("tle");
                       String filt  = rs2.getString("filifino");
                       m3.setText(mt);
                       s3.setText(st);
                       e3.setText(et);
                       t3.setText(tt);
                       f3.setText(filt);
                           int m3int = Integer.parseInt(mt);
                       int s3int = Integer.parseInt(st);
                       int e3int = Integer.parseInt(et);
                       int t3int = Integer.parseInt(tt);
                       int f3int = Integer.parseInt(filt);
                       
                       int sototal3 = m3int+s3int+e3int+t3int+f3int;
                       int total3 = sototal3 /5;
                       String totos3 = String.valueOf(total3);
                       tgt.setText(totos3);
                       String querys3 = "SELECT * FROM `grades4` WHERE fullname = '"+c+"';";
            ResultSet rs3 = stmt.executeQuery(querys3);
             while(rs3.next()){
                   String md  = rs3.getString("math");
                 String sd  = rs3.getString("science");
                   String ed  = rs3.getString("english");
                     String td  = rs3.getString("tle");
                       String fild  = rs3.getString("filifino");
                       m4.setText(md);
                       s4.setText(sd);
                       e4.setText(ed);
                       t4.setText(td);
                       f4.setText(fild);
                           int m4int = Integer.parseInt(md);
                       int s4int = Integer.parseInt(sd);
                       int e4int = Integer.parseInt(ed);
                       int t4int = Integer.parseInt(td);
                       int f4int = Integer.parseInt(fild);
                       
                       int sototal4 = m4int+s4int+e4int+t4int+f4int;
                       int total4 = sototal4 /5;
                       String totos4 = String.valueOf(total4);
                       fc.setText(totos4);
                       int full = total+total2+total3+total4;
                       int fulld = full / 4;
                        String finalx = String.valueOf(fulld);
                       ttt.setText(finalx);
                      
            }
                       
            }
            
            }
                       
               
                       
                     
                             



             
            }
            
            
            
           
           
            
            
            
        } catch (SQLException ex) {
            System.out.println("");
        }
       }     
    }//GEN-LAST:event_comxActionPerformed

    private void spMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spMouseClicked
     
    }//GEN-LAST:event_spMouseClicked

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
     notex.setVisible(true);
     notbtn.setVisible(true);
    }//GEN-LAST:event_jLabel22MouseClicked

    private void notbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notbtnMouseClicked
            try {
            conn db = new conn();
            Statement stmt = db.getconnect();
            
         String  w = (String) ssx.getSelectedItem();
         String sessionu = login.usernamet.getText();
               String txt = notex.getText();
                String query = "insert into notes(`teacher`, `note`, `fullname`)"
                    + " values('"+sessionu+"', '"+txt+"', '"+w+"')"; 
            stmt.execute(query);
      
         
          Component frame = null;
                      JOptionPane.showMessageDialog(frame,
    "OK",
    "Sucess",
    JOptionPane.OK_OPTION);
                      notex.setText("");
  
          
            
            
        } catch (SQLException ex) {
            System.out.println("error: " + ex.getMessage());
        }
    }//GEN-LAST:event_notbtnMouseClicked

    private void jLabel21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel21MouseClicked
             String  w = (String) ssx.getSelectedItem();
         
       
        try {
          
           
           
               
            conn db = new conn();
            Statement stmt = db.getconnect();
             String query = "UPDATE users\n" +
"SET status='1'\n" +
"WHERE fullname='"+w+"'"; 
            stmt.execute(query);
            statusz.setText("Drop Out");
        Component frame = null;
                      JOptionPane.showMessageDialog(frame,
    "OK",
    "Sucess",
    JOptionPane.OK_OPTION);
  
           } catch (SQLException ex) {
            System.out.println("error: " + ex.getMessage());
            
        }
    }//GEN-LAST:event_jLabel21MouseClicked

    private void ssxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ssxActionPerformed
  String  w = (String) ssx.getSelectedItem();
         if (ssx.getSelectedItem().equals("Select Student"))
       {
        statusz.setText("N/A");
       }else{
         
         
        try {
          
            conn db = new conn();
            Statement stmt = db.getconnect();


              String querys = "select * from users where fullname = '"+w+"';"; 
            ResultSet rs = stmt.executeQuery(querys);
         



            while (rs.next()) {
              
            String status = rs.getString("status");
            if(status.equals("1")){
                statusz.setText("Drop out");
            }else{
                statusz.setText("Enrolled");
            }
            
            
              
              
            

            }
                     
                
    
             
        } catch (SQLException ex) {
            System.out.println("error: " + ex.getMessage());
        }    
         }
    }//GEN-LAST:event_ssxActionPerformed

    private void btnonoffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnonoffMouseClicked
   try {
          
            conn db = new conn();
            Statement stmt = db.getconnect();
             String querys = "SELECT * FROM `config` WHERE id = '1'"; 
            ResultSet rs = stmt.executeQuery(querys);
  
            while (rs.next()) {
               // System.out.println("first name: " + rs.getString("email"));
               String idz = rs.getString("id");
               String x = rs.getString("darkmode");
       
      
        if(x.equals("0")){
            side.setBackground(new java.awt.Color(0, 0, 0));
            btnonoff.setText("ON");
            String query = "UPDATE config\n" +
"SET darkmode='1'\n" +
"WHERE id='1'"; 
            stmt.execute(query);
        }else if(x.equals("1")){
            side.setBackground(new java.awt.Color(0, 51, 204));
            btnonoff.setText("OFF");
            String query = "UPDATE config\n" +
"SET darkmode='0'\n" +
"WHERE id='1'"; 
            stmt.execute(query);
            
        }
          
            }
             
        } catch (SQLException ex) {
            System.out.println("");
        }
        
        
       
    }//GEN-LAST:event_btnonoffMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      if(click ==0){
          CPPANEL.setVisible(true);
          click = 1;
      }else if(click == 1){
          CPPANEL.setVisible(false);
          click = 0;
      }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
           
            
       
        try {
          
           
           String fullnam = login.usernamet.getText();
               String o =oldx.getText();
                String n =newp.getText();
               
            conn db = new conn();
            Statement stmt = db.getconnect();
      
      String current= o;
        MessageDigest m=MessageDigest.getInstance("MD5");
        m.update(current.getBytes(),0,current.length());
        pg = new BigInteger(1,m.digest()).toString(16);
        
         String current2= n;
        MessageDigest s=MessageDigest.getInstance("MD5");
        s.update(current2.getBytes(),0,current2.length());
        String pg2 = new BigInteger(1,s.digest()).toString(16);
        
         String querys = "SELECT * FROM `users` WHERE  username = '"+fullnam+"';";
            ResultSet rs = stmt.executeQuery(querys);
         
 
            while (rs.next()) {
               // System.out.println("first name: " + rs.getString("email"));
               String currents  = rs.getString("password");
                 if(pg.equals(currents)){
                      String query = "UPDATE users\n" +
"SET password='"+pg2+"'"+
"WHERE username='"+fullnam+"'"; 
            stmt.execute(query);
             Component frame = null;
                      JOptionPane.showMessageDialog(frame,
    "ok",
    "Sucess",
    JOptionPane.OK_OPTION);
                 }else{
                      Component frame = null;
                      JOptionPane.showMessageDialog(frame,
    "PASSWORD IS INVALID",
    "Sucess",
    JOptionPane.WARNING_MESSAGE);
                 }
            }
        
             
    
            
           } catch (SQLException ex) {
            System.out.println("");
            
        }        catch (NoSuchAlgorithmException ex) {
                     Logger.getLogger(admin.class.getName()).log(Level.SEVERE, null, ex);
                 }
       
  
           
       
    }//GEN-LAST:event_jButton4MouseClicked

    private void jToggleButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton2MouseClicked
       this.setVisible(false);
       login xx= new login();
         login.invokersession.setText("false");
                   
   xx.setVisible(true);
    }//GEN-LAST:event_jToggleButton2MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
         try {
          
           
            String title = TT.getText();
            
               
            conn db = new conn();
            Statement stmt = db.getconnect();
             String query = "UPDATE config\n" +
"SET schoolname='"+title+"'\n" +
"WHERE id='1'"; 
             
            stmt.execute(query);
          TT.setText("");
     String querys = "SELECT * FROM `config` WHERE  id = '1';";
            ResultSet rs = stmt.executeQuery(querys);
         while (rs.next()) {
               // System.out.println("first name: " + rs.getString("email"));
               String titles  = rs.getString("schoolname");
               TT.setText(titles);
         }
      
  
           } catch (SQLException ex) {
            System.out.println("error: " + ex.getMessage());
            
        }
    }//GEN-LAST:event_jButton5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
                 String xz = login.invokersession.getText();
             if(xz.equals("true")){
                  new admin().setVisible(true);
             
                 
            }else{
                new admin().setVisible(false);
        }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JPanel CPPANEL;
    private javax.swing.JPanel Settings;
    public static javax.swing.JTextField TT;
    private javax.swing.JPanel admin_adduser;
    private javax.swing.JPanel admin_managestudents;
    private javax.swing.JPanel admin_setgrades;
    public static javax.swing.JToggleButton btnonoff;
    private javax.swing.JTextField cfullname;
    private javax.swing.JComboBox<String> comx;
    private javax.swing.JLabel e1;
    private javax.swing.JLabel e2;
    private javax.swing.JLabel e3;
    private javax.swing.JLabel e4;
    private javax.swing.JTextField englishtf;
    private javax.swing.JLabel f1;
    private javax.swing.JLabel f2;
    private javax.swing.JLabel f3;
    private javax.swing.JLabel f4;
    private javax.swing.JLabel fc;
    private javax.swing.JLabel fgt;
    private javax.swing.JTextField filtf;
    private javax.swing.JPanel fp;
    private javax.swing.JLabel fpt;
    private javax.swing.JLabel fptt;
    private javax.swing.JPanel ftp;
    private javax.swing.JComboBox<String> grading;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JLabel m1;
    private javax.swing.JLabel m2;
    private javax.swing.JLabel m3;
    private javax.swing.JLabel m4;
    private javax.swing.JTextField mathtf;
    private javax.swing.JPanel mother;
    private javax.swing.JTextField newp;
    private javax.swing.JButton notbtn;
    private javax.swing.JTextArea notex;
    private javax.swing.JTextField oldx;
    private javax.swing.JPanel paneltab;
    private javax.swing.JComboBox<String> pos;
    private javax.swing.JLabel s1;
    private javax.swing.JLabel s2;
    private javax.swing.JLabel s3;
    private javax.swing.JLabel s4;
    private javax.swing.JTextField sciencetf;
    private javax.swing.JLabel sgt;
    public static javax.swing.JPanel side;
    private javax.swing.JPanel sp;
    private javax.swing.JLabel spt;
    private javax.swing.JComboBox<String> ssx;
    private javax.swing.JLabel statusz;
    private javax.swing.JTextField stdn;
    private javax.swing.JTabbedPane switcher;
    private javax.swing.JLabel t1;
    private javax.swing.JLabel t2;
    private javax.swing.JLabel t3;
    private javax.swing.JLabel t4;
    private javax.swing.JLabel tgt;
    private javax.swing.JTextField tletf;
    private javax.swing.JTextField tot;
    private javax.swing.JPanel tp;
    private javax.swing.JLabel tpt;
    private javax.swing.JLabel ttt;
    // End of variables declaration//GEN-END:variables



}
