/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package student.information.system;

import java.awt.Component;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.security.*;
import java.math.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import static student.information.system.admin.CPPANEL;
import static student.information.system.student.welco;

/**
 *
 * @author home
 */

public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
         boolean sessionlog = true;
          try {
 conn db = new conn();
            Statement stmt = db.getconnect();
            
     String querys = "SELECT * FROM `config` WHERE  id = '1';";
            ResultSet rs = stmt.executeQuery(querys);
         while (rs.next()) {
               // System.out.println("first name: " + rs.getString("email"));
               String titles  = rs.getString("schoolname");
               schoolname.setText(titles);
         
         }
      
  
           } catch (SQLException ex) {
            System.out.println("error: " + ex.getMessage());
            
        }
       
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
     String username  = "";
String password = "";
int prv = 0;
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        schoolname = new javax.swing.JLabel();
        usernamet = new javax.swing.JTextField();
        passwordt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        invokersession = new javax.swing.JLabel();
        hfn = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setForeground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(null);

        schoolname.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        schoolname.setForeground(new java.awt.Color(51, 51, 51));
        schoolname.setText("School Name");
        schoolname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                schoolnameMouseClicked(evt);
            }
        });
        jPanel1.add(schoolname);
        schoolname.setBounds(130, 70, 230, 20);

        usernamet.setText("Username");
        usernamet.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        usernamet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernametActionPerformed(evt);
            }
        });
        jPanel1.add(usernamet);
        usernamet.setBounds(110, 110, 180, 30);

        passwordt.setText("password");
        jPanel1.add(passwordt);
        passwordt.setBounds(110, 160, 180, 30);

        jButton1.setText("Login");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(160, 200, 70, 23);

        invokersession.setText("false");
        jPanel1.add(invokersession);
        invokersession.setBounds(220, 120, 23, 14);

        hfn.setText("hiddenfname");
        jPanel1.add(hfn);
        hfn.setBounds(150, 120, 62, 14);

        jLabel1.setText("TEST ACCOUNTS");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 240, 90, 14);

        jLabel2.setText("ADMIN:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 260, 80, 14);

        jLabel3.setText("Student:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 290, 70, 14);

        jLabel4.setForeground(new java.awt.Color(204, 0, 51));
        jLabel4.setText("username:johnsmithx password:9898");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(80, 290, 270, 14);

        jLabel5.setForeground(new java.awt.Color(255, 0, 51));
        jLabel5.setText("username:qwerty password:qwerty");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(80, 260, 250, 14);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void schoolnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_schoolnameMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_schoolnameMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        try {
            String x =usernamet.getText();
            String y = passwordt.getText();
            conn db = new conn();
            Statement stmt = db.getconnect();
             String querys = "SELECT * FROM `users` WHERE username = '"+x+"'"; 
            ResultSet rs = stmt.executeQuery(querys);
  
            while (rs.next()) {
               // System.out.println("first name: " + rs.getString("email"));
               String idz = rs.getString("id");
               username = rs.getString("username");
               String fullnamez = rs.getString("fullname");
          password = rs.getString("password");
          prv = rs.getInt("previllege");
          
          
          
          
                  String current= y;
        MessageDigest m=MessageDigest.getInstance("MD5");
        m.update(current.getBytes(),0,current.length());
        String passworddb = new BigInteger(1,m.digest()).toString(16);
        if(x.equals(username) && passworddb.equals(password)){
            if(prv == 1){
                this.setVisible(false);
                admin xz= new admin();
                admin.CPPANEL.setVisible(false);
                invokersession.setText("true");
               

   xz.setVisible(true);
            }else if(prv == 0){
                 hfn.setText(fullnamez);
                 invokersession.setText("true");
          
                this.setVisible(false);
                student xx= new student();
                   
   xx.setVisible(true);
            }
            
        }if(!passworddb.equals(password)){
             Component frame = null;
                      JOptionPane.showMessageDialog(frame,
    "Invalid password",
    "opps",
    JOptionPane.WARNING_MESSAGE);
        }
            }
                     
            
    
             
        } catch (SQLException ex) {
            System.out.println("error: " + ex.getMessage());
        } catch (NoSuchAlgorithmException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void usernametActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernametActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernametActionPerformed

    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {
       
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new login().setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel hfn;
    public static javax.swing.JLabel invokersession;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField passwordt;
    private javax.swing.JLabel schoolname;
    public static javax.swing.JTextField usernamet;
    // End of variables declaration//GEN-END:variables

  
    


}
